// One-shot generator. Run: node scripts/build-prompts.mjs
import { writeFileSync } from "node:fs";

const meta = {
  categories: [
    "Cinematic Brand",
    "Talking Head",
    "Product",
    "Motion Control",
    "Image\u2192Video",
    "Character Consistency",
    "Couple & Lifestyle",
    "Dialogue Scene",
    "Photo Realism",
    "Viral Hook",
  ],
  tools: [
    "Veo 3.1 Standard",
    "Veo 3.1 Fast",
    "Kling 2.6 Pro",
    "Kling v3 Pro",
    "Sora 2",
    "Sora 2 Pro",
    "Seedance 1.5 Pro",
    "Wan 2.6",
    "Hailuo 2.3",
    "Luma Ray 2",
    "PixVerse V5.5",
    "LTXV 2",
  ],
};

export const items = [];

items.push({
  id: "veo-cafe-jazz",
  title: "Cafe rainy window, jazz ambient",
  category: "Cinematic Brand",
  tool: "Veo 3.1 Standard",
  difficulty: "Menengah",
  preview: "Barista menuang latte art di kafe berjendela hujan, uap naik perlahan, jazz pelan terdengar.",
  subject: "Barista wanita 28 tahun, apron linen krem, rambut diikat rendah, di belakang bar kayu walnut.",
  action: "[00:00\u201300:03] Menuang susu dari pitcher tinggi membentuk rosetta pelan. [00:03\u201300:06] Mengangkat cangkir, sedikit memutar, meletakkan di saucer. [00:06\u201300:08] Pandangan naik singkat ke kamera lalu kembali ke cangkir.",
  shot: "Medium close-up, 50mm spherical, shallow depth of field f/2.0, slow dolly-in 12cm, eye-level, 24fps 180\u00b0 shutter.",
  lighting: "Window key dari kiri pukul 16:00 difus oleh hujan, warm tungsten fill 2700K dari belakang bar, cool rim biru dari jendela basah. Palette anchors: walnut brown, cream, amber, slate blue.",
  audio: "Ambient: gerimis di kaca, mesin espresso berdesis pelan. SFX: sendok logam mengetuk porselen di akhir tuangan. Music: trio jazz tenang -22 LUFS, no vocals.",
  negative: "lengan tambahan, pitcher teleport, latte art glitch, signage merek, watermark, oversaturated highlights, plastic skin",
  tags: ["barista", "rain", "jazz", "veo3"],
});
items.push({
  id: "kling-night-runner",
  title: "Night runner, neon parallax",
  category: "Cinematic Brand",
  tool: "Kling 2.6 Pro",
  difficulty: "Lanjutan",
  preview: "Pelari malam di trotoar Jakarta, neon toko buram berkilau di belakang, langkah konsisten 8 detik.",
  subject: "Pelari pria 26 tahun, jaket teknis hitam reflektif, sneaker putih bersih, jam GPS di pergelangan kiri.",
  action: "[00:00\u201300:02] Tiga langkah memasuki frame dari kanan. [00:02\u201300:06] Tracking sejajar selama empat langkah, lengan ayun simetris. [00:06\u201300:08] Memperlambat langkah, menoleh sekilas ke kamera, keluar frame kiri.",
  shot: "Tracking shot dari samping, 35mm anamorphic 2x squeeze, depth of field menengah, kecepatan kamera match dengan langkah subjek, handheld halus dengan stabilizer.",
  lighting: "Neon practicals merah-pink dari papan toko di latar, streetlight natrium 2200K sebagai key punggung, refleksi basah pada aspal sebagai fill cool. Palette: jet black, hot pink, sodium amber, asphalt grey.",
  audio: "Ambient: kota malam, gerimis tipis. SFX: footsteps konsisten 170 BPM, jaket bergesekan ringan. No music.",
  negative: "kaki menyilang aneh, sepatu berubah bentuk, neon over-bloom, signage huruf rusak, motion blur agresif, frame goyang",
  tags: ["running", "neon", "tracking", "anamorphic"],
});
items.push({
  id: "sora-product-water",
  title: "Sneaker hits puddle, splash physics",
  category: "Cinematic Brand",
  tool: "Sora 2 Pro",
  difficulty: "Menengah",
  preview: "Sneaker putih menginjak genangan, percikan air bersih dengan physics realistis 12 detik.",
  subject: "Sneaker performance putih bersih, tali abu-abu, tanpa logo terbaca; permukaan aspal basah dengan genangan dangkal 3cm.",
  action: "[00:00\u201300:04] Sneaker turun perlahan dari atas frame. [00:04\u201300:06] Sol menyentuh permukaan air, percikan radial bersih setinggi 20cm. [00:06\u201300:10] Air kembali tenang, riak menyebar ke tepi frame. [00:10\u201300:12] Sneaker mengangkat, tetes terakhir jatuh.",
  shot: "Low-angle macro, 50mm equivalent, deep focus, kamera diam, framing simetris, 1080p portrait 9:16.",
  lighting: "Softbox top-down sebagai key, dua reflector silver di sisi kanan-kiri untuk highlight tepi air. Palette: bone white, slate, mirror blue.",
  audio: "SFX: splash bersih dengan tail tetesan. Ambient: ruang studio mati. No dialogue, no music.",
  negative: "logo merek, tetesan tembus sneaker, riak tidak menyebar, motion blur, refleksi kamera, smoothing permukaan air",
  tags: ["product", "physics", "splash", "sora2"],
});
items.push({
  id: "veo-talking-head-ceo",
  title: "Founder talking head, 8 detik",
  category: "Talking Head",
  tool: "Veo 3.1 Standard",
  difficulty: "Menengah",
  preview: "Founder berbicara langsung ke kamera, lipsync presisi, tone profesional dan hangat.",
  subject: "Founder wanita 34 tahun, blazer wol charcoal, kemeja krem polos, rambut sebahu, anting kecil emas.",
  action: "[00:00\u201300:02] Kontak mata dengan kamera, sedikit miring kepala. [00:02\u201300:07] Berbicara satu kalimat utuh, gestur tangan kanan halus di luar frame. [00:07\u201300:08] Senyum tipis menutup kalimat.",
  shot: "Medium close-up dada ke atas, 85mm, f/2.8, eye-level, framing 3/4 sedikit ke kiri, kamera diam.",
  lighting: "Soft key kiri 45\u00b0 5600K, fill kanan dengan reflector cream, hair light cool dari belakang, latar abu lembut. Palette: charcoal, cream, soft grey, skin warm.",
  audio: "Dialogue: \"Kami bangun ini untuk creator yang capek nge-prompt acak, bukan untuk demo.\" Ambient: ruang tertutup sangat tenang. No music.",
  negative: "lipsync miss, mata juling, plastic skin, kepala bergerak liar, tangan masuk frame tiba-tiba, makeup heavy",
  tags: ["talking head", "founder", "lipsync"],
});
items.push({
  id: "seedance-multilang-host",
  title: "Multilingual host intro, lipsync",
  category: "Talking Head",
  tool: "Seedance 1.5 Pro",
  difficulty: "Lanjutan",
  preview: "Host membuka konten dalam Bahasa Indonesia dengan lipsync presisi, transisi mulus antar shot.",
  subject: "Host pria 30 tahun, kemeja linen biru tua lengan digulung, latar dinding tekstur kapur abu hangat.",
  action: "[00:00\u201300:02] Menatap kamera, mengangguk pelan sebagai sapaan. [00:02\u201300:09] Membicarakan satu kalimat pengantar dengan gestur ringan. [00:09\u201300:12] Menutup dengan senyum dan mengangkat cangkir kopi sebentar.",
  shot: "Medium shot 35mm, eye-level, depth of field menengah, framing center, kamera diam dengan micro-handheld 1\u00b0 drift.",
  lighting: "Window light kiri 5200K diffused, fill kanan reflector white, latar diberi practical lamp warm 2700K untuk pemisahan. Palette: indigo, terracotta, bone, warm grey.",
  audio: "Dialogue (id-ID): \"Halo, hari ini kita bahas cara nyusun prompt yang nggak bikin kamu buang credit.\" SFX: cangkir keramik diletakkan pelan. Ambient: ruangan tenang.",
  negative: "lipsync drift, mulut over-articulated, gigi berlebihan, tangan masuk frame tanpa motivasi, mata bergeser",
  tags: ["host", "indonesian", "lipsync", "seedance"],
});
items.push({
  id: "hailuo-fast-emote",
  title: "Reaction close-up, B-roll cepat",
  category: "Talking Head",
  tool: "Hailuo 2.3",
  difficulty: "Pemula",
  preview: "Close-up reaksi natural untuk B-roll konten emosional, generate dibawah 30 detik.",
  subject: "Wanita 22 tahun, hoodie krem, rambut diikat ekor kuda, latar dinding kayu blur lembut.",
  action: "[00:00\u201300:02] Ekspresi netral, kedipan natural. [00:02\u201300:04] Alis sedikit naik, senyum kecil tumbuh perlahan. [00:04\u201300:06] Tertawa pelan satu beat, kepala miring 5\u00b0.",
  shot: "Close-up wajah, 85mm, f/2.0, eye-level, kamera diam, framing 9:16.",
  lighting: "Window key kiri natural 5500K, fill kanan reflector cream, latar fall-off gelap. Palette: cream, oat, walnut, skin warm.",
  audio: "SFX: tawa pelan satu beat di 00:04. Ambient: ruangan tenang. No dialogue, no music.",
  negative: "ekspresi morphing, gigi berubah jumlah, mata bergeser, plastic skin, smoothing kulit, makeup heavy",
  tags: ["reaction", "b-roll", "fast"],
});
items.push({
  id: "veo-product-perfume",
  title: "Perfume bottle, soft luxury 4s",
  category: "Product",
  tool: "Veo 3.1 Fast",
  difficulty: "Pemula",
  preview: "Botol parfum kaca berputar perlahan di alas marmer, cahaya soft luxury, audio mati.",
  subject: "Botol parfum kaca bening 50ml, cap emas brushed, label minimalis tanpa teks terbaca, alas marmer Calacatta putih.",
  action: "[00:00\u201300:04] Rotasi 360\u00b0 searah jarum jam dengan kecepatan konstan, kap menghadap kamera saat 00:02.",
  shot: "Static low-angle hero, 50mm, f/4.0 deep focus, framing simetris, 1080p landscape 16:9.",
  lighting: "Softbox 4x6 dari kiri sebagai key 5600K, gridded back light untuk separasi, gobo tipis di lantai marmer. Palette: bone white, gold, cream marble, soft shadow grey.",
  audio: "Mute. Optional: room tone -45 dB.",
  negative: "label dengan teks terbaca, refleksi kamera, distorsi botol, gerakan goyang, motion blur, jari masuk frame",
  tags: ["product", "perfume", "rotation", "luxury"],
});
items.push({
  id: "wan-product-multishot",
  title: "Skincare multi-shot narrative",
  category: "Product",
  tool: "Wan 2.6",
  difficulty: "Menengah",
  preview: "Tiga shot pendek skincare: hero, tekstur, hand model, dirangkai dalam 10 detik.",
  subject: "Botol serum kaca bening 30ml dengan dropper, label krem polos, tangan model perempuan tanpa kuteks.",
  action: "[00:00\u201300:04] Hero static botol di atas alas linen oat. [00:04\u201300:07] Macro tekstur serum jatuh dari dropper ke punggung tangan. [00:07\u201300:10] Hand model menutup botol perlahan, keluar frame kanan.",
  shot: "Shot 1: medium static 50mm. Shot 2: macro 100mm f/4.0. Shot 3: medium tracking pelan 35mm. Continuity color sama di tiga shot.",
  lighting: "Window light north-facing 5500K diffused, white card bounce dari kanan, latar dinding warm grey. Palette: oat, bone, glass clear, soft amber.",
  audio: "Ambient room tone. SFX: tetesan dropper di 00:05. No dialogue, no music.",
  negative: "label dengan brand asli, tangan ekstra, jari menyatu, serum bocor di luar tangan, motion blur agresif",
  tags: ["skincare", "multi-shot", "macro", "wan"],
});
items.push({
  id: "pixverse-product-i2v",
  title: "Foto produk jadi clip dinamis",
  category: "Product",
  tool: "PixVerse V5.5",
  difficulty: "Pemula",
  preview: "Foto produk diubah jadi clip 5 detik dengan parallax, refleksi cahaya bergeser, dan kain bergerak.",
  subject: "Subjek persis dari foto referensi. Posisi, label, sudut, dan warna dipertahankan identik.",
  action: "[00:00\u201300:02] Refleksi highlight bergeser pelan dari kanan ke kiri di permukaan produk. [00:02\u201300:04] Kain latar bergerak halus oleh angin pelan. [00:04\u201300:05] Settle ke frame akhir mirip frame awal.",
  shot: "Static framing identik dengan foto referensi. Tanpa zoom, tanpa pan. 50mm equivalent.",
  lighting: "Mengikuti lighting foto referensi. Tidak menambahkan key light baru, hanya gerakan refleksi yang sudah ada.",
  audio: "Mute, atau room tone tipis -50 dB.",
  negative: "produk berpindah, label berubah, refleksi kamera, geometri produk berubah, warna oversaturate, latar bergeser drastis",
  tags: ["i2v", "product", "ambient", "pixverse"],
});
items.push({
  id: "kling-motion-control-dance",
  title: "Dance reference \u2192 character",
  category: "Motion Control",
  tool: "Kling 2.6 Pro",
  difficulty: "Lanjutan",
  preview: "Transfer 15 detik gerakan dance dari video referensi ke karakter AI, lighting dan tubuh konsisten.",
  subject: "Karakter wanita 24 tahun dari character reference, oversize tee putih, baggy denim hitam, sneaker chunky.",
  action: "Motion Control: gunakan video referensi 15 detik (uploaded) sebagai timeline gerakan. Karakter mengikuti choreography persis frame demi frame, tanpa mengubah tempo atau ritme.",
  shot: "Locked-off medium-wide 35mm, eye-level, framing center, kamera diam, ground line stabil.",
  lighting: "Single key spot 5600K dari atas-depan 30\u00b0, fill ringan dari kanan untuk anti silhouette, latar gradient ungu ke charcoal. Palette: charcoal, lavender, bone, skin neutral.",
  audio: "Music: track yang sama dengan referensi (di-mute jika lisensi tidak jelas, biarkan kosong agar editor menambahkan). SFX: footsteps mengikuti beat.",
  negative: "spaghetti limbs, kaki menembus lantai, drift posisi, tempo tidak match, jari menyatu, outfit berubah di tengah",
  tags: ["motion control", "dance", "kling"],
});
items.push({
  id: "kling-motion-action-spar",
  title: "Sparring drill, full-body physics",
  category: "Motion Control",
  tool: "Kling v3 Pro",
  difficulty: "Lanjutan",
  preview: "Sparring drill 8 detik dengan full-body physics konsisten dari video referensi pelatih.",
  subject: "Atlet pria 28 tahun, rashguard hitam, celana training abu, sarung tangan MMA merah marun, latar gym beton ekspos.",
  action: "Motion Control: video referensi pelatih melakukan jab-cross-hook 4 kombinasi. Karakter menjalankan kombinasi yang sama dengan timing identik. [00:00\u201300:08].",
  shot: "Tracking medium 35mm, sedikit handheld, kecepatan kamera mengikuti rotasi torso, framing kepala-ke-paha.",
  lighting: "Practical industrial dari plafon 4500K dengan grid, rim light biru pelan dari belakang, fall-off cepat ke shadow. Palette: charcoal, oxblood, slate, bone.",
  audio: "SFX: kepalan menampar pad keras, napas pendek 2 kali, footwork di matras. Ambient: gym kosong. No music.",
  negative: "lengan bertumpang, sarung tangan menembus tubuh, kaki kehilangan ground, motion blur agresif, frame goyang",
  tags: ["motion control", "sport", "kling"],
});
items.push({
  id: "veo-i2v-portrait",
  title: "Foto portrait jadi video subtle",
  category: "Image\u2192Video",
  tool: "Veo 3.1 Fast",
  difficulty: "Pemula",
  preview: "Foto portrait diubah jadi clip 4 detik dengan kepala miring halus, kedipan natural, rambut bergerak.",
  subject: "Persis seperti foto referensi. Pakaian, rambut, latar, ekspresi awal dipertahankan.",
  action: "[00:00\u201300:01] Kedipan halus. [00:01\u201300:03] Kepala miring 4\u00b0 ke kanan dan kembali. [00:03\u201300:04] Senyum tipis tumbuh perlahan tanpa membuka mulut.",
  shot: "Static framing identik dengan referensi, tanpa zoom, tanpa pan, 50mm equivalent, depth of field mengikuti referensi.",
  lighting: "Mengikuti lighting foto referensi. Tidak menambahkan key light baru.",
  audio: "Mute, atau room tone -50 dB.",
  negative: "wajah berubah, baju berganti warna, latar bergeser, anggota badan tambahan, ekspresi melompat, lipsync palsu",
  tags: ["i2v", "portrait", "veo3"],
});
items.push({
  id: "luma-i2v-landscape",
  title: "Landscape jadi shot sinematik",
  category: "Image\u2192Video",
  tool: "Luma Ray 2",
  difficulty: "Menengah",
  preview: "Foto pegunungan jadi shot sinematik 6 detik dengan parallax, awan bergerak, kabut naik.",
  subject: "Pemandangan dari foto referensi: pegunungan dengan kabut tipis di lembah, foreground rumput pendek, langit pagi clear.",
  action: "[00:00\u201300:03] Awan bergerak pelan ke kanan dengan kecepatan natural. [00:03\u201300:05] Kabut di lembah naik perlahan, parallax foreground subtle. [00:05\u201300:06] Settle frame akhir.",
  shot: "Slow dolly-in 30cm, 24mm wide, deep focus, sedikit tilt-up 2\u00b0 di akhir.",
  lighting: "Mengikuti referensi: golden hour pagi, key dari kanan, kabut sebagai natural diffuser. Palette: cobalt sky, oat grass, slate rock, soft amber.",
  audio: "Ambient: angin lembut, kicau burung jauh. No music, no dialogue.",
  negative: "objek bergerak random, warna oversaturate, glitch geometri, oversharpened, awan flicker, parallax patah",
  tags: ["i2v", "landscape", "luma"],
});
items.push({
  id: "wan-i2v-architecture",
  title: "Foto arsitektur jadi orbit shot",
  category: "Image\u2192Video",
  tool: "Wan 2.6",
  difficulty: "Menengah",
  preview: "Foto bangunan brutalist diubah jadi orbit 10 detik dengan parallax foreground dan langit bergerak.",
  subject: "Bangunan beton ekspos dari referensi, garis horizontal kuat, kanopi menjorok, tanaman kecil di base.",
  action: "[00:00\u201300:08] Orbit 25\u00b0 ke kanan dengan radius konstan, parallax foreground tanaman bergerak lebih cepat. [00:08\u201300:10] Settle, awan tipis di langit terus bergerak.",
  shot: "Slow orbit 25\u00b0, 24mm, deep focus, eye-level. Stabilisasi tinggi, no roll.",
  lighting: "Overcast diffuse dari atas, ambient occlusion natural pada coakan beton. Palette: concrete grey, moss, bone sky, deep shadow.",
  audio: "Ambient: angin, kota jauh. No dialogue, no music.",
  negative: "geometri bangunan berubah, jendela bergeser, parallax patah, langit oversaturated, bayangan flicker",
  tags: ["i2v", "architecture", "orbit", "wan"],
});
items.push({
  id: "sora-character-consistency",
  title: "Same character across 3 scenes",
  category: "Character Consistency",
  tool: "Sora 2 Pro",
  difficulty: "Lanjutan",
  preview: "Karakter sama tampil konsisten di tiga scene berbeda menggunakan Sora 2 Characters API.",
  subject: "Character ID terdaftar (mis. char_alia). Wanita 27 tahun, jaket bomber sage, kemeja putih, sneaker putih, tas kanvas oat.",
  action: "Scene 1 [00:00\u201300:05] berjalan keluar dari stasiun MRT. Scene 2 [00:05\u201300:10] duduk di bangku taman membuka buku. Scene 3 [00:10\u201300:15] menyeberang zebra cross dengan dua langkah cepat lalu lima langkah biasa.",
  shot: "Scene 1: medium tracking 35mm. Scene 2: static medium close-up 50mm f/2.8. Scene 3: low-angle wide 24mm tracking. Continuity wardrobe dan rambut identik.",
  lighting: "Sore hari clear, key matahari dari kanan-belakang, fill ambient kota. Palette: sage, bone, asphalt grey, warm amber, blush.",
  audio: "Ambient kota: bus jauh, footsteps di trotoar, percakapan jauh sebagai bed -28 LUFS. SFX: bel zebra cross di scene 3.",
  negative: "wajah berubah antar scene, outfit berganti warna, tas hilang, rambut berubah panjang, plastic skin, parallax patah",
  tags: ["sora characters", "consistency", "multi-scene"],
});
items.push({
  id: "veo-ingredients-detective",
  title: "Detective scene, ingredients-to-video",
  category: "Character Consistency",
  tool: "Veo 3.1 Standard",
  difficulty: "Lanjutan",
  preview: "Dialog detektif dan saksi dengan tiga reference image: detektif, saksi, kantor. Lipsync rapi.",
  subject: "Detektif pria 40-an dari ref-1, saksi wanita 30-an dari ref-2, kantor noir dari ref-3. Wardrobe dan setting dipertahankan persis.",
  action: "[00:00\u201300:03] Medium shot detektif di belakang meja, melihat ke saksi. [00:03\u201300:08] Cut over-shoulder ke saksi yang menatap balik. Detektif berbicara satu kalimat, saksi menjawab satu kalimat.",
  shot: "Shot 1: medium 50mm eye-level. Shot 2: over-shoulder 50mm sedikit lebih tinggi. Continuity arah pandang 180\u00b0 rule.",
  lighting: "Single tungsten desk lamp 2700K sebagai practical, fill kanan tipis, deep shadow di belakang. Palette: tobacco, charcoal, amber lamp, smoke grey.",
  audio: "Dialogue:\nDetective: \"Of all the offices in this town, you walked into mine.\"\nWitness: \"You were highly recommended.\"\nSFX: kursi kayu berderit pelan. Ambient: ventilasi kota malam.",
  negative: "wajah morphing antar shot, lipsync miss, mata bergeser, kursi teleport, tangan tambahan, gigi berubah",
  tags: ["dialogue", "noir", "veo3", "ingredients"],
});
items.push({
  id: "kling-couple-cafe",
  title: "Couple ngobrol di cafe, candid",
  category: "Couple & Lifestyle",
  tool: "Kling 2.6 Pro",
  difficulty: "Menengah",
  preview: "Pasangan ngobrol pelan di kafe sore, sesekali tertawa kecil, suasana hangat dan candid.",
  subject: "Pasangan 20-an. Subjek A: kemeja oxford biru muda, rambut belah samping. Subjek B: cardigan krem, anting kecil, rambut bob.",
  action: "[00:00\u201300:03] Saling memandang, tangan kanan mengaduk kopi. [00:03\u201300:06] B tertawa kecil satu beat, A ikut tersenyum. [00:06\u201300:08] A menyandar ke depan, tangan kiri mendekat ke cangkir.",
  shot: "Locked-off medium two-shot 35mm, sedikit handheld 1\u00b0 drift, eye-level, framing rule of thirds.",
  lighting: "Window light kanan jam 16:00, warm tungsten practical dari belakang bar, latar bokeh hangat. Palette: cream, oak, walnut, honey, soft pink.",
  audio: "Ambient: kafe ramai sedang -22 LUFS. SFX: sendok mengetuk porselen di 00:04. No dialogue.",
  negative: "tangan menyatu, gelas teleport, ekspresi morphing, lipsync palsu, kepala saling menembus",
  tags: ["couple", "cafe", "candid"],
});
items.push({
  id: "kling-couple-walk-park",
  title: "Pasangan jalan di taman pagi",
  category: "Couple & Lifestyle",
  tool: "Kling v3 Pro",
  difficulty: "Menengah",
  preview: "Pasangan jalan santai bergandengan, daun bergerak ringan, tracking shot 8 detik.",
  subject: "Pasangan 20-an, outfit casual. Subjek A: jaket linen oat, jeans relaxed. Subjek B: dress katun mocha, sneaker putih.",
  action: "[00:00\u201300:02] Memasuki frame dari kanan, langkah sinkron. [00:02\u201300:06] Tangan kanan A memegang tangan kiri B, sesekali saling pandang. [00:06\u201300:08] A berbisik singkat, B tertawa pelan.",
  shot: "Tracking dari samping, 35mm, eye-level, framing pinggang ke atas, kecepatan kamera match dengan langkah.",
  lighting: "Golden hour pagi 6500K dari kiri-belakang, fill kabut tipis taman, daun sebagai natural gobo. Palette: oat, mocha, sage, warm amber, sky cream.",
  audio: "Ambient: taman pagi, burung kecil, langkah di gravel. SFX: gesekan jaket linen. No dialogue terbaca.",
  negative: "tangan menyatu jadi satu, langkah tidak sinkron, drift posisi, ekspresi morphing, latar bergeser",
  tags: ["couple", "park", "tracking"],
});
items.push({
  id: "veo-dialogue-restaurant",
  title: "Restaurant scene, 2 character dialog",
  category: "Dialogue Scene",
  tool: "Veo 3.1 Standard",
  difficulty: "Lanjutan",
  preview: "Adegan restoran 8 detik dengan dua karakter bicara bergantian, ambience restoran realistis.",
  subject: "Karakter A: pria 35 tahun, sweater navy, jam tangan kulit. Karakter B: wanita 33 tahun, blouse silk pearl, anting drop kecil. Meja kayu walnut, dua gelas air.",
  action: "[00:00\u201300:04] A meletakkan gelas, melihat ke B sambil bicara. [00:04\u201300:08] B menjawab pelan, sedikit tersenyum, jari bermain di tepi gelas.",
  shot: "Shot 1: medium A 50mm. Shot 2: reverse medium B 50mm. 180\u00b0 rule dipatuhi, eye-level, depth of field shallow.",
  lighting: "Practical pendant warm 2700K di atas meja, ambient resto fall-off ke shadow lembut. Palette: walnut, navy, pearl, candle amber.",
  audio: "Dialogue:\nA: \"Aku nggak nyangka kamu beneran datang.\"\nB: \"Aku juga nggak nyangka aku iya.\"\nAmbient: restoran sedang ramai -24 LUFS, peralatan makan berdenting jauh.",
  negative: "lipsync miss, gelas teleport, jari menembus gelas, kepala saling menembus, plastic skin",
  tags: ["dialogue", "restaurant", "veo3"],
});
items.push({
  id: "veo-photoreal-portrait",
  title: "Photoreal portrait, north window",
  category: "Photo Realism",
  tool: "Veo 3.1 Standard",
  difficulty: "Menengah",
  preview: "Portrait realistis dengan tekstur kulit alami, kontak mata stabil, gerakan sangat halus.",
  subject: "Wanita 28 tahun, rambut hitam panjang sedikit bergelombang, sweater rajut krem, latar dinding kapur abu hangat.",
  action: "[00:00\u201300:02] Tatapan stabil ke kamera, kedipan natural. [00:02\u201300:05] Kepala miring 3\u00b0 ke kanan dan kembali. [00:05\u201300:08] Senyum tipis tumbuh tanpa membuka mulut.",
  shot: "Medium close-up dada ke atas, 85mm, f/1.8, eye-level, kamera diam, framing rule of thirds.",
  lighting: "Window light north-facing 5500K sebagai key dari kiri, fill reflector cream tipis dari kanan, hair light cool dari belakang. Palette: cream, oat, charcoal, skin warm.",
  audio: "Mute, atau room tone -50 dB, ambient AC pelan.",
  negative: "plastic skin, AI glow, smoothing pori, mata simetri sempurna, makeup heavy, gigi terlihat saat senyum tertutup",
  tags: ["portrait", "realism", "skin"],
});
items.push({
  id: "sora-photoreal-street",
  title: "Tokyo backstreet, 35mm push 800",
  category: "Photo Realism",
  tool: "Sora 2",
  difficulty: "Lanjutan",
  preview: "Adegan jalanan Tokyo malam dengan grain film natural, refleksi neon di trotoar basah, 12 detik.",
  subject: "Pejalan kaki dengan payung transparan, mantel hujan oversize abu, latar gang sempit dengan signage non-spesifik.",
  action: "[00:00\u201300:04] Berjalan dari kanan ke kiri 4 langkah. [00:04\u201300:08] Berhenti, melihat ke arah signage di belakang. [00:08\u201300:12] Melanjutkan jalan, keluar frame kiri.",
  shot: "35mm spherical, f/1.4, push ISO setara 800, motion blur ringan natural, framing 16:9, slight handheld.",
  lighting: "Mixed practicals: neon merah-pink dari kiri, sodium amber dari belakang, refleksi basah di trotoar sebagai natural fill cool. Black Pro-Mist 1/4 di lensa. Palette: jet, hot pink, sodium amber, ink blue, asphalt grey.",
  audio: "Ambient: gerimis pelan, kota malam jauh, langkah di aspal basah. No dialogue, no music.",
  negative: "neon over-bloom, signage huruf rusak, oversharpened, oversaturated, distorsi wajah, payung berubah bentuk",
  tags: ["street", "tokyo", "night", "film"],
});
items.push({
  id: "ltxv-4k-talking",
  title: "4K interview, locked-off",
  category: "Photo Realism",
  tool: "LTXV 2",
  difficulty: "Menengah",
  preview: "Interview style talking head 4K dengan kontrol pipeline rapi, frame stabil 12 detik.",
  subject: "Engineer wanita 32 tahun, kemeja oxford putih, blazer abu navy, latar studio gelap dengan rim lembut.",
  action: "[00:00\u201300:04] Pengantar singkat ke kamera. [00:04\u201300:09] Mengembangkan satu kalimat utama dengan gestur tangan ringan. [00:09\u201300:12] Menutup dengan senyum tipis dan kedipan natural.",
  shot: "Locked-off medium close-up 85mm, f/2.8, eye-level, 4K UHD 24fps, framing 3/4.",
  lighting: "Soft box 5x5 kiri 5600K key, gridded back light biru tipis, latar fall-off ke charcoal. Palette: charcoal, navy, bone, soft blue rim.",
  audio: "Dialogue: \"Kalau kamu nge-prompt seperti ngarahin DOP, hasilnya beda.\" Ambient: studio mati. No music.",
  negative: "lipsync miss, plastic skin, mata juling, makeup heavy, kepala bergerak liar, frame goyang",
  tags: ["interview", "4k", "ltxv"],
});
items.push({
  id: "hailuo-viral-hook-question",
  title: "Hook 3 detik, pertanyaan langsung",
  category: "Viral Hook",
  tool: "Hailuo 2.3",
  difficulty: "Pemula",
  preview: "Pembukaan 3 detik 9:16 dengan close-up subjek melempar pertanyaan langsung ke kamera.",
  subject: "Subjek wanita 24 tahun, kemeja oversize krem, anting kecil, rambut diikat rendah.",
  action: "[00:00\u201300:01] Tatapan langsung ke kamera, kepala diam. [00:01\u201300:03] Mengucapkan pertanyaan singkat, alis sedikit naik di akhir kalimat.",
  shot: "Close-up dada ke atas 35mm, f/2.0, eye-level, framing 9:16, kamera diam.",
  lighting: "Window key kiri 5500K, fill kanan reflector cream, latar bokeh hangat. Palette: cream, oat, walnut, skin warm.",
  audio: "Dialogue: \"Kenapa hasil AI kamu masih kayak gitu-gitu aja?\" Ambient: ruangan tenang. No music.",
  negative: "ekspresi berlebihan, gestur tangan random, latar mengganggu, lipsync miss, mata bergeser",
  tags: ["hook", "vertical", "shorts"],
});
items.push({
  id: "veo-viral-reveal",
  title: "Reveal hook, tilt-up 4 detik",
  category: "Viral Hook",
  tool: "Veo 3.1 Fast",
  difficulty: "Menengah",
  preview: "Kamera mulai dari objek detail di tangan lalu tilt-up reveal subjek utama, audio sinkron.",
  subject: "Detail tangan memegang notebook moleskine kecil, halaman terbuka dengan tulisan tangan kabur. Subjek utama: pria 29 tahun, kemeja oxford biru muda.",
  action: "[00:00\u201300:02] Tangan menutup notebook pelan. [00:02\u201300:04] Tilt-up dari notebook ke wajah subjek, fokus rack mengikuti.",
  shot: "Tilt-up 4 detik, 35mm, f/2.8, fokus rack dari objek ke wajah, framing 9:16.",
  lighting: "Window light kiri 5500K, lamp practical hangat di kanan. Palette: navy, walnut, cream, paper white.",
  audio: "SFX: notebook ditutup pelan dengan elastic snap. Ambient: ruang kerja tenang. Dialogue tipis di akhir: \"Yang kamu cari, ada di sini.\"",
  negative: "rack focus gagal, frame goyang, objek berubah bentuk, signage merek, lipsync miss",
  tags: ["reveal", "tilt-up", "hook"],
});
items.push({
  id: "pixverse-pov-hook",
  title: "POV hook, first-person grip",
  category: "Viral Hook",
  tool: "PixVerse V5.5",
  difficulty: "Menengah",
  preview: "Sudut POV first-person 5 detik. Tangan meraih objek di kafe pagi, hook ringan dan organic.",
  subject: "Tangan subjek di foreground, kuku natural tanpa kuteks; objek: cangkir keramik kecil di atas saucer kayu, latar kafe pagi.",
  action: "[00:00\u201300:02] Tangan masuk frame dari bawah, jari membuka. [00:02\u201300:04] Memegang cangkir dengan grip natural, mengangkat pelan. [00:04\u201300:05] Cangkir keluar bawah frame.",
  shot: "POV first-person 24mm wide, sedikit handheld, fokus dekat 30cm, framing 9:16.",
  lighting: "Window light alami pagi 5800K dari kanan, ambient reflektor cream. Palette: cream, oat, walnut, latte foam.",
  audio: "SFX: keramik di saucer, sendok kecil. Ambient: kafe pagi, mesin espresso jauh. No dialogue.",
  negative: "jari menyatu, objek tembus tangan, grip aneh, latar gelap, motion blur agresif",
  tags: ["pov", "first person", "hook"],
});

const out = { categories: meta.categories, tools: meta.tools, items };
writeFileSync("src/data/prompts.json", JSON.stringify(out, null, 2) + "\n");
console.log("wrote", items.length, "items");
